version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taches
      MYSQL_USER: user
      MYSQL_PASSWORD: p
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springnet

  springboot:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/taches
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: p
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql
    networks:
      - springnet

volumes:
  mysql-data:

networks:
  springnet: